.TH "VIDEO" "1" "24 August 2008" "" ""
.SH "NAME"
video \- MythNetTV video processing module
.SH "DESCRIPTION"
 \fBmythnettv\fP is a RSS video aggregtor for MythTV.  It take 
 downloads video feeds and places them in the recording directory
 in MythTV, then makes them accessible with the rest of your 
 recordings.

 The MythNetTV video subsystem may be queried directly. This
 can be useful if you want to perform simple operations such
 as asking if a given video file needs to be transcoded before
 being imported into MythTV, or actually performing the
 transcode.

.SH "USAGE"

 length <path>       : return the length of a video in seconds
 info <path>         : return all available information for a
                       given video
 needstranscode <path>
                     : determine if a given file needs to be
                       transcoded before being imported into
                       MythTV
 transcode <path> <output path>
                     : transcode the file into a format
                       suitable for MythTV

.SH "CONTACT DETAILS"
Information about \fBmythnettv\fP is posted to \fBhttp://www.stillhq.com/mythtv/mythnettv/\fP regularly. There is a users mailing list at \fBhttp://lists.stillhq.com/listinfo.cgi/mythnettv-stillhq.com\fP

.SH "AUTHOR"
\fBmythnettv\fP is by Michael Still <mikal@stillhq.com>

